AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CPC User Pools

  User Pools for  Calmpitt's Pest Control

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      UserPoolName: CPC User Pool
  DefaultUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: Default
      GenerateSecret: false
      RefreshTokenValidity: 30
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Description: "The ID for the user pool"
    Value: !Ref UserPool
